find -name '*.html' -print0 | xargs -0 -I {} sed -ie 's/Mailus@Experts.com/contacto@idg.com/' {}
#find -name '*.html' -print0 | xargs -0 -I {} sed -ie 's///' {}
#find -name '*.html' -print0 | xargs -0 -I {} sed -ie 's///' {}
#find -name '*.html' -print0 | xargs -0 -I {} sed -ie 's///' {}
#find -name '*.html' -print0 | xargs -0 -I {} sed -ie 's///' {}
#find -name '*.html' -print0 | xargs -0 -I {} sed -ie 's///' {}
#find -name '*.html' -print0 | xargs -0 -I {} sed -ie 's///' {}
#find -name '*.html' -print0 | xargs -0 -I {} sed -ie 's///' {}
#find -name '*.html' -print0 | xargs -0 -I {} sed -ie 's///' {}
#find -name '*.html' -print0 | xargs -0 -I {} sed -ie 's///' {}
#find -name '*.html' -print0 | xargs -0 -I {} sed -ie 's///' {}
#find -name '*.html' -print0 | xargs -0 -I {} sed -ie 's///' {}
#find -name '*.html' -print0 | xargs -0 -I {} sed -ie 's///' {}
#find -name '*.html' -print0 | xargs -0 -I {} sed -ie 's///' {}
#find -name '*.html' -print0 | xargs -0 -I {} sed -ie 's///' {}
#find -name '*.html' -print0 | xargs -0 -I {} sed -ie 's///' {}
